steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'docker.io/joshiaman112/flask-backend:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'docker.io/joshiaman112/flask-backend:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - instances
      - update-container
      - joshi-assign2-flask-backend
      - --container-image
      - docker.io/joshiaman112/flask-backend:latest
      - --zone
      - northamerica-northeast2-a

options:
  logging: CLOUD_LOGGING_ONLY
